import type { GlobalThemeOverrides } from 'naive-ui'

export const shineMageTheme = {
  color: {
    background: '#09050D',
    backgroundTop: '#0F0B17',
    backgroundMiddle: '#120D1D',
    backgroundBottom: '#0A0711',
    brandPrimary: '#805D9D',
    brandPrimaryHover: '#9877B1',
    brandPrimaryPressed: '#674482',
    brandSecondary: '#D3C3E8',
    brandAccent: '#F2FFDC',
    ink: '#FEFCFF',
    inkOnAccent: '#201426',
    copyStrong: '#ECE5F0',
    copy: '#C4B8CB',
    muted: '#9A8BA4',
    faint: '#6F6078',
    danger: '#FF7D91',
    success: '#10B981',
    warning: '#F59E0B',
  },
  font: {
    body: "'Alibaba PuHuiTi 3.0', 'Alibaba PuHuiTi', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif",
    display: "'Outfit', 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif",
    mono: "'SFMono-Regular', 'SF Mono', Menlo, Monaco, Consolas, monospace",
  },
  radius: {
    panel: '18px',
    control: '12px',
    soft: '10px',
    pill: '999px',
  },
  material: {
    line: 'rgba(211, 195, 232, 0.12)',
    lineStrong: 'rgba(211, 195, 232, 0.24)',
    lineAccent: 'rgba(242, 255, 220, 0.22)',
    lineAccentStrong: 'rgba(242, 255, 220, 0.72)',
    glass: 'linear-gradient(145deg, rgba(35, 21, 44, 0.78), rgba(17, 10, 23, 0.72))',
    glassSubtle: 'rgba(255, 255, 255, 0.03)',
    glassStrong: 'rgba(27, 15, 35, 0.96)',
    glassInput: 'rgba(5, 2, 8, 0.42)',
    overlay: 'rgba(5, 2, 8, 0.72)',
    nav: 'rgba(9, 5, 13, 0.90)',
    navActive: 'rgba(211, 195, 232, 0.12)',
    signalSoft: 'rgba(242, 255, 220, 0.06)',
    signalLine: 'rgba(242, 255, 220, 0.16)',
    purpleSoft: 'rgba(128, 93, 157, 0.12)',
    purpleGlow: 'rgba(128, 93, 157, 0.28)',
    lilacFaint: 'rgba(211, 195, 232, 0.30)',
    gridLine: 'rgba(211, 195, 232, 0.10)',
    whiteTopLine: 'rgba(255, 255, 255, 0.18)',
    whiteFaint: 'rgba(255, 255, 255, 0.025)',
    whiteSoft: 'rgba(255, 255, 255, 0.06)',
    dangerSoft: 'rgba(255, 125, 145, 0.08)',
  },
  gradient: {
    background: 'linear-gradient(180deg, #0F0B17 0%, #120D1D 48%, #0A0711 100%)',
    primary: 'linear-gradient(135deg, #805D9D 0%, #674482 100%)',
    secondary: 'linear-gradient(90deg, #805D9D 0%, #D3C3E8 100%)',
    metric: 'linear-gradient(96deg, #FEFCFF 0%, #D3C3E8 54%, #F2FFDC 100%)',
    answer: 'linear-gradient(135deg, rgba(128, 93, 157, 0.10), rgba(242, 255, 220, 0.025))',
    chip: 'linear-gradient(135deg, rgba(128, 93, 157, 0.12), rgba(211, 195, 232, 0.035))',
    loginHero: 'radial-gradient(circle at 66% 22%, rgba(128, 93, 157, 0.38), transparent 35%), linear-gradient(145deg, #160B1E, #09050D 74%)',
    loginShade: 'linear-gradient(90deg, rgba(9, 5, 13, 0.08), rgba(9, 5, 13, 0.52)), linear-gradient(0deg, rgba(9, 5, 13, 0.82), transparent 60%)',
    loginPanel: 'radial-gradient(circle at 80% 18%, rgba(128, 93, 157, 0.13), transparent 30%), #0A0711',
  },
  shadow: {
    panel: 'inset 0 1px 0 rgba(211, 195, 232, 0.18), 0 20px 50px rgba(0, 0, 0, 0.50), 0 0 30px rgba(128, 97, 157, 0.10)',
    focus: '0 0 0 2px rgba(128, 93, 157, 0.50), 0 0 30px rgba(128, 93, 157, 0.18)',
    button: 'inset 0 1px 0 rgba(255, 255, 255, 0.26), 0 14px 34px rgba(0, 0, 0, 0.34), 0 0 24px rgba(128, 93, 157, 0.20)',
    buttonHover: 'inset 0 1px 0 rgba(255, 255, 255, 0.34), 0 18px 42px rgba(0, 0, 0, 0.42), 0 0 34px rgba(128, 93, 157, 0.34)',
    navActive: 'inset 0 1px 0 rgba(211, 195, 232, 0.16), 0 0 24px rgba(128, 93, 157, 0.12)',
    signal: '0 0 18px rgba(242, 255, 220, 0.18)',
  },
  blur: {
    panel: 'blur(26px) saturate(125%)',
    nav: 'blur(24px) saturate(130%)',
    overlay: 'blur(16px)',
  },
  motion: {
    fast: '160ms cubic-bezier(0.2, 0.8, 0.2, 1)',
    standard: '240ms cubic-bezier(0.2, 0.8, 0.2, 1)',
  },
} as const

export const shineMageCssVariables = {
  '--sm-bg': shineMageTheme.color.background,
  '--sm-bg-top': shineMageTheme.color.backgroundTop,
  '--sm-bg-middle': shineMageTheme.color.backgroundMiddle,
  '--sm-bg-bottom': shineMageTheme.color.backgroundBottom,
  '--sm-purple': shineMageTheme.color.brandPrimary,
  '--sm-purple-hover': shineMageTheme.color.brandPrimaryHover,
  '--sm-purple-pressed': shineMageTheme.color.brandPrimaryPressed,
  '--sm-lilac': shineMageTheme.color.brandSecondary,
  '--sm-signal': shineMageTheme.color.brandAccent,
  '--sm-ink': shineMageTheme.color.ink,
  '--sm-on-accent': shineMageTheme.color.inkOnAccent,
  '--sm-copy-strong': shineMageTheme.color.copyStrong,
  '--sm-copy': shineMageTheme.color.copy,
  '--sm-muted': shineMageTheme.color.muted,
  '--sm-faint': shineMageTheme.color.faint,
  '--sm-danger': shineMageTheme.color.danger,
  '--sm-line': shineMageTheme.material.line,
  '--sm-line-strong': shineMageTheme.material.lineStrong,
  '--sm-line-accent': shineMageTheme.material.lineAccent,
  '--sm-line-accent-strong': shineMageTheme.material.lineAccentStrong,
  '--sm-glass': shineMageTheme.material.glass,
  '--sm-glass-subtle': shineMageTheme.material.glassSubtle,
  '--sm-glass-strong': shineMageTheme.material.glassStrong,
  '--sm-glass-input': shineMageTheme.material.glassInput,
  '--sm-overlay': shineMageTheme.material.overlay,
  '--sm-nav': shineMageTheme.material.nav,
  '--sm-nav-active': shineMageTheme.material.navActive,
  '--sm-signal-soft': shineMageTheme.material.signalSoft,
  '--sm-signal-line': shineMageTheme.material.signalLine,
  '--sm-purple-soft': shineMageTheme.material.purpleSoft,
  '--sm-purple-glow': shineMageTheme.material.purpleGlow,
  '--sm-lilac-faint': shineMageTheme.material.lilacFaint,
  '--sm-grid-line': shineMageTheme.material.gridLine,
  '--sm-white-top-line': shineMageTheme.material.whiteTopLine,
  '--sm-white-faint': shineMageTheme.material.whiteFaint,
  '--sm-white-soft': shineMageTheme.material.whiteSoft,
  '--sm-danger-soft': shineMageTheme.material.dangerSoft,
  '--sm-gradient-bg': shineMageTheme.gradient.background,
  '--sm-gradient-primary': shineMageTheme.gradient.primary,
  '--sm-gradient-secondary': shineMageTheme.gradient.secondary,
  '--sm-gradient-metric': shineMageTheme.gradient.metric,
  '--sm-gradient-answer': shineMageTheme.gradient.answer,
  '--sm-gradient-chip': shineMageTheme.gradient.chip,
  '--sm-gradient-login-hero': shineMageTheme.gradient.loginHero,
  '--sm-gradient-login-shade': shineMageTheme.gradient.loginShade,
  '--sm-gradient-login-panel': shineMageTheme.gradient.loginPanel,
  '--sm-shadow-panel': shineMageTheme.shadow.panel,
  '--sm-shadow-focus': shineMageTheme.shadow.focus,
  '--sm-shadow-button': shineMageTheme.shadow.button,
  '--sm-shadow-button-hover': shineMageTheme.shadow.buttonHover,
  '--sm-shadow-nav-active': shineMageTheme.shadow.navActive,
  '--sm-shadow-signal': shineMageTheme.shadow.signal,
  '--sm-blur-panel': shineMageTheme.blur.panel,
  '--sm-blur-nav': shineMageTheme.blur.nav,
  '--sm-blur-overlay': shineMageTheme.blur.overlay,
  '--sm-radius-panel': shineMageTheme.radius.panel,
  '--sm-radius-control': shineMageTheme.radius.control,
  '--sm-radius-soft': shineMageTheme.radius.soft,
  '--sm-radius-pill': shineMageTheme.radius.pill,
  '--sm-font-display': shineMageTheme.font.display,
  '--sm-font-body': shineMageTheme.font.body,
  '--sm-font-mono': shineMageTheme.font.mono,
  '--sm-motion-fast': shineMageTheme.motion.fast,
  '--sm-motion-standard': shineMageTheme.motion.standard,
} as const

export function applyShineMageTheme(root: HTMLElement = document.documentElement) {
  for (const [name, value] of Object.entries(shineMageCssVariables)) {
    root.style.setProperty(name, value)
  }
}

export const naiveThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: shineMageTheme.color.brandPrimary,
    primaryColorHover: shineMageTheme.color.brandPrimaryHover,
    primaryColorPressed: shineMageTheme.color.brandPrimaryPressed,
    primaryColorSuppl: shineMageTheme.color.brandSecondary,
    successColor: shineMageTheme.color.success,
    warningColor: shineMageTheme.color.warning,
    errorColor: shineMageTheme.color.danger,
    fontFamily: shineMageTheme.font.body,
    fontFamilyMono: shineMageTheme.font.mono,
    fontWeight: '400',
    fontWeightStrong: '600',
    borderRadius: shineMageTheme.radius.soft,
    borderRadiusSmall: '8px',
  },
  Button: {
    borderRadiusMedium: shineMageTheme.radius.control,
    borderRadiusSmall: shineMageTheme.radius.soft,
    fontWeight: '500',
  },
  Card: { borderRadius: shineMageTheme.radius.panel },
  Menu: {
    borderRadius: shineMageTheme.radius.soft,
    itemHeight: '36px',
    itemBorderRadius: shineMageTheme.radius.pill,
  },
  Select: { peers: { InternalSelection: { borderRadius: shineMageTheme.radius.control } } },
  DatePicker: { borderRadius: shineMageTheme.radius.control },
}
