import type { FreeHtmlPage, PageAdapters, LocateResult, PreviewRecord } from './mock-adapters.d.mts';

export type FreeHtmlLibraryState = {
  view: 'home' | 'workspace';
  viewportWidth: number;
  railCollapsed: boolean;
  prompt: string;
  designGuide: { kind?: string; loaded?: boolean; excerpt?: string; error?: string } | null;
  skill: { loaded?: boolean; excerpt?: string; error?: string } | null;
  dataContext: { attached?: boolean; label?: string } | null;
  assetsExpanded: boolean;
  assets: unknown[];
  pages: ReturnType<PageAdapters['assets']['list']>;
  current: FreeHtmlPage | null;
  mode: 'browse' | 'edit';
  selection: (LocateResult & { stale?: boolean; ok?: boolean }) | null;
  contextPanel: 'ai' | 'source' | 'history' | null;
  overlay: 'selection' | 'patch' | null;
  preview: PreviewRecord | null;
  confirmationUncertain: boolean;
  lastIdempotencyKey: string | null;
  pendingLeaveIntent: string | null;
  busy: boolean;
  message: string;
  liveStatus: string;
  hostError: string;
  inspector: unknown;
  previewAlive: boolean;
  adapterKind: string;
  nativeChatReachable: boolean;
};

export type FreeHtmlLibraryStore = {
  subscribe(listener: () => void): () => void;
  getSnapshot(): FreeHtmlLibraryState;
  hasUnsavedChanges(): boolean;
  hasActiveEditContext(): boolean;
  dispose(): void;
  adapters: PageAdapters;
  samplePrompts: readonly string[];
  setPrompt(value: string): void;
  setViewport(width: number): void;
  toggleRail(): void;
  setRailOpen(open: boolean): void;
  setDesignGuide(guide: FreeHtmlLibraryState['designGuide']): void;
  setSkill(skill: FreeHtmlLibraryState['skill']): void;
  setDataContext(dataContext: FreeHtmlLibraryState['dataContext']): void;
  toggleAssets(): void;
  applyExample(text: string): void;
  generate(): Promise<void>;
  openPage(pageId: string): void;
  requestLeave(intent: string): { blocked: boolean; hasUnsavedChanges: boolean; hasActiveEditContext: boolean };
  enterEdit(): void;
  exitEdit(): void;
  selectLocatable(request: Record<string, unknown>): void;
  selectWholePage(): void;
  clearSelection(): void;
  openContext(panel: 'ai' | 'source' | 'history'): void;
  closeContext(): void;
  previewPatch(instruction: string, extras?: Record<string, unknown>): Promise<void>;
  confirmExpandedPatch(): void;
  confirmPatch(): Promise<void>;
  cancelPreview(): Promise<void>;
  saveDraft(): Promise<void>;
  markLocalDraft(pkg: FreeHtmlPage['package']): void;
  rollback(version: number): Promise<void>;
  inspectConfirmation(): void;
  stopPreview(): void;
  restartPreview(): void;
  inspectCurrent(): void;
  closeOverlay(): Promise<void> | void;
  layout(): { band: string; rail: string; panel: string; pointerEvents: 'none' | 'auto'; srcdoc: string };
};

export function createFreeHtmlLibraryStore(opts?: {
  adapters?: PageAdapters;
  now?: () => number;
  viewportWidth?: number;
}): FreeHtmlLibraryStore;
