coordinator=true
node-scheduler.include-coordinator=false
http-server.http.port=8080
discovery-server.enabled=true
discovery.uri=http://trino-coordinator:8080

query.max-memory=8GB
query.max-memory-per-node=4GB
query.max-total-memory=12GB
query.client.timeout=10m
exchange.compression-codec=ZSTD
