/** Fixture for Figma 03 StaffDeck. Not a live roster. */
export const STAFF_FIXTURE = Object.freeze([
  Object.freeze({
    id: 'growth-analyst',
    name: '增长分析师',
    role: '渠道 × 首购承接',
    desc: '问可核验的经营问题，结论与口径分开。',
    tags: Object.freeze(['口径严谨', '可追溯']),
    docs: 2, skills: 1, sops: 3,
    mine: true,
  }),
  Object.freeze({
    id: 'ops-advisor',
    name: '经营参谋',
    role: '零售 GSV 诊断',
    desc: '先给数字，再给建议，UNKNOWN 不编。',
    tags: Object.freeze(['口径严谨', '可追溯']),
    docs: 2, skills: 1, sops: 3,
    mine: true,
  }),
  Object.freeze({
    id: 'data-qa',
    name: '数据质检',
    role: 'DQ 本地告警',
    desc: '合成边界内工作，不接飞书 token。',
    tags: Object.freeze(['口径严谨', '可追溯']),
    docs: 2, skills: 1, sops: 3,
    mine: false,
  }),
  Object.freeze({
    id: 'sop-coach',
    name: 'SOP 教练',
    role: '员工流程入口',
    desc: '流程留飞书，这里只做入口。',
    tags: Object.freeze(['口径严谨', '可追溯']),
    docs: 2, skills: 1, sops: 3,
    mine: false,
  }),
  Object.freeze({
    id: 'board-editor',
    name: '看板编辑',
    role: '成板与换展示',
    desc: '点块改字改图标，不改口径。',
    tags: Object.freeze(['口径严谨', '可追溯']),
    docs: 2, skills: 1, sops: 3,
    mine: false,
  }),
  Object.freeze({
    id: 'legal',
    name: '法务顾问',
    role: '口径与权限',
    desc: '不写 SQL，审批另走。',
    tags: Object.freeze(['口径严谨', '可追溯']),
    docs: 2, skills: 1, sops: 3,
    mine: false,
  }),
]);
